# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created: Mon Feb 22 13:44:19 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(623, 274)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.TimeLimitLine = QtGui.QLineEdit(self.groupBox_4)
        self.TimeLimitLine.setStyleSheet(_fromUtf8("font: 12pt \"仿宋\";"))
        self.TimeLimitLine.setObjectName(_fromUtf8("TimeLimitLine"))
        self.gridLayout_3.addWidget(self.TimeLimitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        spacerItem1 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_7)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.TargetUnitLine = QtGui.QLineEdit(self.groupBox_6)
        self.TargetUnitLine.setStyleSheet(_fromUtf8("font: 12pt \"宋体\";"))
        self.TargetUnitLine.setObjectName(_fromUtf8("TargetUnitLine"))
        self.gridLayout_5.addWidget(self.TargetUnitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.ScoreUnitLine = QtGui.QLineEdit(self.groupBox_5)
        self.ScoreUnitLine.setStyleSheet(_fromUtf8("font: 12pt \"宋体\";"))
        self.ScoreUnitLine.setObjectName(_fromUtf8("ScoreUnitLine"))
        self.gridLayout_4.addWidget(self.ScoreUnitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lable_4 = QtGui.QLabel(Dialog)
        self.lable_4.setObjectName(_fromUtf8("lable_4"))
        self.gridLayout_2.addWidget(self.lable_4, 0, 0, 1, 1)
        self.Level1Edit = QtGui.QLineEdit(Dialog)
        self.Level1Edit.setObjectName(_fromUtf8("Level1Edit"))
        self.gridLayout_2.addWidget(self.Level1Edit, 0, 1, 1, 1)
        self.Level2Edit = QtGui.QLineEdit(Dialog)
        self.Level2Edit.setObjectName(_fromUtf8("Level2Edit"))
        self.gridLayout_2.addWidget(self.Level2Edit, 0, 2, 1, 1)
        self.Level3Edit = QtGui.QLineEdit(Dialog)
        self.Level3Edit.setObjectName(_fromUtf8("Level3Edit"))
        self.gridLayout_2.addWidget(self.Level3Edit, 0, 3, 1, 1)
        self.Level4Edit = QtGui.QLineEdit(Dialog)
        self.Level4Edit.setObjectName(_fromUtf8("Level4Edit"))
        self.gridLayout_2.addWidget(self.Level4Edit, 0, 4, 1, 1)
        self.Level5Edit = QtGui.QLineEdit(Dialog)
        self.Level5Edit.setObjectName(_fromUtf8("Level5Edit"))
        self.gridLayout_2.addWidget(self.Level5Edit, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.Level6Edit = QtGui.QLineEdit(Dialog)
        self.Level6Edit.setObjectName(_fromUtf8("Level6Edit"))
        self.gridLayout_6.addWidget(self.Level6Edit, 0, 1, 1, 1)
        self.Level7Edit = QtGui.QLineEdit(Dialog)
        self.Level7Edit.setObjectName(_fromUtf8("Level7Edit"))
        self.gridLayout_6.addWidget(self.Level7Edit, 0, 2, 1, 1)
        self.Level8Edit = QtGui.QLineEdit(Dialog)
        self.Level8Edit.setObjectName(_fromUtf8("Level8Edit"))
        self.gridLayout_6.addWidget(self.Level8Edit, 0, 3, 1, 1)
        self.Level9Edit = QtGui.QLineEdit(Dialog)
        self.Level9Edit.setObjectName(_fromUtf8("Level9Edit"))
        self.gridLayout_6.addWidget(self.Level9Edit, 0, 4, 1, 1)
        self.Level10Edit = QtGui.QLineEdit(Dialog)
        self.Level10Edit.setObjectName(_fromUtf8("Level10Edit"))
        self.gridLayout_6.addWidget(self.Level10Edit, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.Level11Edit = QtGui.QLineEdit(Dialog)
        self.Level11Edit.setObjectName(_fromUtf8("Level11Edit"))
        self.gridLayout_7.addWidget(self.Level11Edit, 0, 1, 1, 1)
        self.Level12Edit = QtGui.QLineEdit(Dialog)
        self.Level12Edit.setObjectName(_fromUtf8("Level12Edit"))
        self.gridLayout_7.addWidget(self.Level12Edit, 0, 2, 1, 1)
        self.Level13Edit = QtGui.QLineEdit(Dialog)
        self.Level13Edit.setObjectName(_fromUtf8("Level13Edit"))
        self.gridLayout_7.addWidget(self.Level13Edit, 0, 3, 1, 1)
        self.Level14Edit = QtGui.QLineEdit(Dialog)
        self.Level14Edit.setObjectName(_fromUtf8("Level14Edit"))
        self.gridLayout_7.addWidget(self.Level14Edit, 0, 4, 1, 1)
        self.Level15Edit = QtGui.QLineEdit(Dialog)
        self.Level15Edit.setObjectName(_fromUtf8("Level15Edit"))
        self.gridLayout_7.addWidget(self.Level15Edit, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.Level16Edit = QtGui.QLineEdit(Dialog)
        self.Level16Edit.setObjectName(_fromUtf8("Level16Edit"))
        self.gridLayout_8.addWidget(self.Level16Edit, 0, 1, 1, 1)
        self.Level17Edit = QtGui.QLineEdit(Dialog)
        self.Level17Edit.setObjectName(_fromUtf8("Level17Edit"))
        self.gridLayout_8.addWidget(self.Level17Edit, 0, 2, 1, 1)
        self.Level18Edit = QtGui.QLineEdit(Dialog)
        self.Level18Edit.setObjectName(_fromUtf8("Level18Edit"))
        self.gridLayout_8.addWidget(self.Level18Edit, 0, 3, 1, 1)
        self.Level19Edit = QtGui.QLineEdit(Dialog)
        self.Level19Edit.setObjectName(_fromUtf8("Level19Edit"))
        self.gridLayout_8.addWidget(self.Level19Edit, 0, 4, 1, 1)
        self.Level20Edit = QtGui.QLineEdit(Dialog)
        self.Level20Edit.setObjectName(_fromUtf8("Level20Edit"))
        self.gridLayout_8.addWidget(self.Level20Edit, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 0, 0, 1, 1)
        self.ComfirmBtn = QtGui.QPushButton(Dialog)
        self.ComfirmBtn.setObjectName(_fromUtf8("ComfirmBtn"))
        self.gridLayout_9.addWidget(self.ComfirmBtn, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 2, 1, 1)
        self.CancelBtn = QtGui.QPushButton(Dialog)
        self.CancelBtn.setObjectName(_fromUtf8("CancelBtn"))
        self.gridLayout_9.addWidget(self.CancelBtn, 0, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 4, 1, 1)
        self.ResetBtn = QtGui.QPushButton(Dialog)
        self.ResetBtn.setObjectName(_fromUtf8("ResetBtn"))
        self.gridLayout_9.addWidget(self.ResetBtn, 0, 5, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem12, 0, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "关卡时限", None))
        self.label_8.setText(_translate("Dialog", "关卡数", None))
        self.comboBox.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox.setItemText(3, _translate("Dialog", "4", None))
        self.comboBox.setItemText(4, _translate("Dialog", "5", None))
        self.comboBox.setItemText(5, _translate("Dialog", "6", None))
        self.comboBox.setItemText(6, _translate("Dialog", "7", None))
        self.comboBox.setItemText(7, _translate("Dialog", "8", None))
        self.comboBox.setItemText(8, _translate("Dialog", "9", None))
        self.comboBox.setItemText(9, _translate("Dialog", "10", None))
        self.comboBox.setItemText(10, _translate("Dialog", "11", None))
        self.comboBox.setItemText(11, _translate("Dialog", "12", None))
        self.comboBox.setItemText(12, _translate("Dialog", "13", None))
        self.comboBox.setItemText(13, _translate("Dialog", "14", None))
        self.comboBox.setItemText(14, _translate("Dialog", "15", None))
        self.comboBox.setItemText(15, _translate("Dialog", "16", None))
        self.comboBox.setItemText(16, _translate("Dialog", "17", None))
        self.comboBox.setItemText(17, _translate("Dialog", "18", None))
        self.comboBox.setItemText(18, _translate("Dialog", "19", None))
        self.comboBox.setItemText(19, _translate("Dialog", "20", None))
        self.label_4.setText(_translate("Dialog", "人均目标", None))
        self.label_3.setText(_translate("Dialog", "目标分值", None))
        self.lable_4.setText(_translate("Dialog", "  1 - 5 关:", None))
        self.label_5.setText(_translate("Dialog", "  6 -10 关:", None))
        self.label_6.setText(_translate("Dialog", "  11-15 关:", None))
        self.label_7.setText(_translate("Dialog", "  16-20 关:", None))
        self.ComfirmBtn.setText(_translate("Dialog", "完成", None))
        self.CancelBtn.setText(_translate("Dialog", "取消", None))
        self.ResetBtn.setText(_translate("Dialog", "恢复默认", None))

