# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(867, 162)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.TimeLimitLine = QtGui.QLineEdit(self.groupBox_4)
        self.TimeLimitLine.setStyleSheet(_fromUtf8("font: 12pt \"仿宋\";"))
        self.TimeLimitLine.setObjectName(_fromUtf8("TimeLimitLine"))
        self.gridLayout_3.addWidget(self.TimeLimitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        spacerItem1 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_7)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.TargetUnitLine = QtGui.QLineEdit(self.groupBox_6)
        self.TargetUnitLine.setStyleSheet(_fromUtf8("font: 12pt \"宋体\";"))
        self.TargetUnitLine.setObjectName(_fromUtf8("TargetUnitLine"))
        self.gridLayout_5.addWidget(self.TargetUnitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.ScoreUnitLine = QtGui.QLineEdit(self.groupBox_5)
        self.ScoreUnitLine.setStyleSheet(_fromUtf8("font: 12pt \"宋体\";"))
        self.ScoreUnitLine.setObjectName(_fromUtf8("ScoreUnitLine"))
        self.gridLayout_4.addWidget(self.ScoreUnitLine, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 0, 1, 1)
        self.ComfirmBtn = QtGui.QPushButton(Dialog)
        self.ComfirmBtn.setObjectName(_fromUtf8("ComfirmBtn"))
        self.gridLayout_9.addWidget(self.ComfirmBtn, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 2, 1, 1)
        self.CancelBtn = QtGui.QPushButton(Dialog)
        self.CancelBtn.setObjectName(_fromUtf8("CancelBtn"))
        self.gridLayout_9.addWidget(self.CancelBtn, 0, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 4, 1, 1)
        self.ResetBtn = QtGui.QPushButton(Dialog)
        self.ResetBtn.setObjectName(_fromUtf8("ResetBtn"))
        self.gridLayout_9.addWidget(self.ResetBtn, 0, 5, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "关卡时限", None))
        self.label_8.setText(_translate("Dialog", "关卡数", None))
        self.comboBox.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox.setItemText(3, _translate("Dialog", "4", None))
        self.comboBox.setItemText(4, _translate("Dialog", "5", None))
        self.comboBox.setItemText(5, _translate("Dialog", "6", None))
        self.comboBox.setItemText(6, _translate("Dialog", "7", None))
        self.comboBox.setItemText(7, _translate("Dialog", "8", None))
        self.comboBox.setItemText(8, _translate("Dialog", "9", None))
        self.comboBox.setItemText(9, _translate("Dialog", "10", None))
        self.comboBox.setItemText(10, _translate("Dialog", "11", None))
        self.comboBox.setItemText(11, _translate("Dialog", "12", None))
        self.comboBox.setItemText(12, _translate("Dialog", "13", None))
        self.comboBox.setItemText(13, _translate("Dialog", "14", None))
        self.comboBox.setItemText(14, _translate("Dialog", "15", None))
        self.comboBox.setItemText(15, _translate("Dialog", "16", None))
        self.comboBox.setItemText(16, _translate("Dialog", "17", None))
        self.comboBox.setItemText(17, _translate("Dialog", "18", None))
        self.comboBox.setItemText(18, _translate("Dialog", "19", None))
        self.comboBox.setItemText(19, _translate("Dialog", "20", None))
        self.label_4.setText(_translate("Dialog", "人均目标", None))
        self.label_3.setText(_translate("Dialog", "目标分值", None))
        self.ComfirmBtn.setText(_translate("Dialog", "完成", None))
        self.CancelBtn.setText(_translate("Dialog", "取消", None))
        self.ResetBtn.setText(_translate("Dialog", "恢复默认", None))

